### ISSUE TITLE
Strava overlay disappears at z20 or higher

### ISSUE THREAD

**Issue by elevenchars** [emersonveenstra/rapid-power-user-extension#6]
Right now, if you are going past z19 the strava overlay disappears
Here's a [link](https://rapideditor.org/edit#map=20.04/51.06237/-114.08374&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&overlays=StravaHeatmapAll) to a location where I'm having the issue. If you zoom out a bit, you'll notice that the heatmap returns.

**Comment by emersonveenstra** [comment]
Yeah, this is a Rapid issue that I forgot to file with them. Rapid only attempts to get overlay data for the current zoom level and 4 levels before that (so zoom level 20 will only attempt to load 20-16), and Strava only gives imagery up to zoom level 15.

**Comment by emersonveenstra** [comment]
I filed this here: https://github.com/facebook/Rapid/issues/1481

**Comment by emersonveenstra** [comment]
This is fixed in 0.4, there's an option to change the max zoom level
