### ISSUE TITLE
Option to allow only the strava overlay, without redirecting to Rapid editor

### ISSUE THREAD

**Issue by waldyrious** [emersonveenstra/rapid-power-user-extension#7]
For some reason, the best imagery in my area does not load in Rapid. The imagery provider may have implemented some whitelisting for osm.org, or perhaps Rapid needs to update the tiles URL — but either way, I can't use this extension because it forces me to use Rapid which doesn't allow me to use the latest and most detailed imagery for my area. I would still like to use the Strava heatmaps, though, and since I'm on Firefox, I can't yet use the original extension until https://github.com/cmoffroad/id-strava-heatmap-extension/issues/1 is resolve.

So an option to disable the Rapid redirect would be great! :)

**Comment by emersonveenstra** [comment]
I totally get where you're coming from, but this extension is meant to complement Rapid, and as the two editors grow further apart, I don't want to take on the extra step of testing and supporting features in iD as well.

Also, from a community perspective, I think the right thing to do here is fix the iD extension, I'll read through that issue and see if I can help debug it.

**Comment by waldyrious** [comment]
Yeah, that makes sense. I appreciate the consideration and response. And thanks for offering to help out in the other issue! :heart:
