### ISSUE TITLE
Edit button from notes page does not open Rapid

### ISSUE THREAD

**Issue by elevenchars** [emersonveenstra/rapid-power-user-extension#8]
Pressing the edit button on osm.org with an open note results in iD opening instead of Rapid

[Example note link](https://www.openstreetmap.org/note/1013986)

**Comment by emersonveenstra** [comment]
Good catch, I'll add this to 0.4, should be out sometime in the next week depending on reviews, etc.

**Comment by emersonveenstra** [comment]
Realized that Rapid doesn't have a way to automatically load notes from the initial URL hash (https://github.com/facebook/Rapid/issues/1630) so it will only zoom to the position of the note, it won't open or highlight the note, sadly

**Comment by emersonveenstra** [comment]
0.4 has been released, so the Edit button now opens Rapid, with the caveat above
